### PR TITLE
Added support for unboxing enum raw values into enum arrays

### PR DESCRIPTION
**Pull request by mikezs**

### CODE REVIEW

**Comment by JohnSundell** [comment]
Really awesome! Thanks for this @mikezs!

**Comment by mikezs** [comment]
Any ETA for a new release? I'd appreciate one ASAP so we don't get out of sync with pods :)

**Comment by JohnSundell** [comment]
I'll try to find time to resolve the two open issues and make a release with all the fixes (including this PR) tonight or tomorrow :)

**Comment by JohnSundell** [comment]
@mikezs Just published a release: https://github.com/JohnSundell/Unbox/releases/tag/1.4
CocoaPods Trunk has also been updated, so you should be good to go :+1:

**Comment by mikezs** [comment]
Just updated, thanks!

**Pull request merged**
