### PR TITLE
Added podspec, Swift 2 Updates

### PR DESCRIPTION
**Pull request by ashfurrow**
Hey! Checked out the project and it looks really cool! I've updated the code for Swift 2.0 (Xcode stripped some extra spaces, sorry :grimacing:).

I've also created a podspec so that others can find the library and use it easily. I can take care of managing the pod, or you can do it (assuming you've pulled latest from master):

```sh
git tag 0.0.1
git push --tags
pod trunk push Unbox.podspec
```

Open for critiques – just let me know!

### CODE REVIEW

**Comment by JohnSundell** [comment]
Hey @ashfurrow! Just merged the `swift2` branch into `master`, so just rebase against the latest `master` and we'll be good to go :)

**Comment by ashfurrow** [comment]
Sure, will do tomorrow!

**Comment by ashfurrow** [comment]
Cool should be good!

**Comment by JohnSundell** [comment]
Great stuff! Thanks @ashfurrow!

**Pull request merged**
