### PR TITLE
[WIP] Add unboxing to Unboxer

### PR DESCRIPTION
**Pull request by nubbel**
This PR adds two `unbox` overloads that allows to unbox a (optional) dictionary to an `Unboxer`.
It can be seen as an alternative to #92 and a solution to #73, #54.

Usage example:
```swift
struct Model: Unboxable {
  let requiredInt: Int
  let optionalInt: Int?

  init(unboxer: Unboxer) {
    let subUnboxer: Unboxer = unboxer.unbox("required")
    self.requiredInt = subUnboxer.unbox("requiredInt")

    let optionalUnboxer: Unboxer? = unboxer.unbox("optional")
    self.optionalInt = optionalUnboxer?.unbox("requiredInt")
  }
}

let dictionary: UnboxableDictionary = [
  "required": [
    "requiredInt" : "7"
  ],
  "optional": [
    "requiredInt" : "14"
  ]
]

let unboxed: Model = try! Unbox(dictionary)
```

In case the unboxing fails, the error is propagated to the "root" `Unboxer` with the full key path.

@JohnSundell, @clayellis Let me know what you think about this approach. If you like it, I'll put together some tests and add documentation to the README.

### CODE REVIEW

**Comment by clayellis** [comment]
@nubbel I believe the root of the problems presented in #73 and #54 are a level higher. Creating another `struct` that acts as a wrapper to solve the problem seems like in incredible inconvenience. This solution also pollutes the `init` which, in my opinion, is the magic of Unbox. I believe the best solution is up on the level where JSON is actually unboxed as presented in #92.

**Comment by nubbel** [comment]
@clayellis Thanks for your comment!

I think we're trying to solve two different problems. In my case I pass whatever is received from a webservice call to `Unbox()` and want to get the decoded model out. At the point where the call to `Unbox` is made I have no knowledge about the response structure, ie. whether the data of interest is nested under a custom key and what that key is. This is only known to model that handles decoding.

In your case you have that knowledge before starting the unboxing.

In addition, unboxing to an `Unboxer` also helps to decode nested structures into flat objects:
```swift
struct Person: Unboxable {
  let name: String
  let city: String
  let zip: String
  let state: String
  let street: String

  init(unboxer: Unboxer) {
    name = unboxer.unbox("name")

    let address: Unboxer = unboxer.unbox("address")
    city = address.unbox("city")
    zip = address.unbox("zip")
    state = address.unbox("state")
    street = address.unbox("street")
  }
}

let dictionary: UnboxableDictionary = [
  "name": "John",
  "address": [
    "city": "Baviera",
    "zip": "92908",
    "state": "CA",
    "street": "455 Larkspur Dr."
  ]
]

let unboxed: Person = try! Unbox(dictionary)
```
Note: This can also be done with key paths, but requires the structure to be traversed multiple times in the unboxing process.

That said, I think the two solutions presented in #92 and #93 can co-exist and could both be supported by Unbox.

**Comment by clayellis** [comment]
@nubbel Hence why there is an optional unbox method. If you don't know if the key exists or not, make the field optional. 

> "I have no knowledge about the response structure, ie. whether the data of interest is nested under a custom key and what that key is."

If that is the case, then you'll never be able to unbox anything. At some point you have to know the key. The problem you're trying to solve, as far as I understand it, is already solved with optional methods and with key paths. 

We aren't trying to solve the same problem. Mine is unsolved and yours has already been solved by the author.

**Comment by JohnSundell** [comment]
@nubbel Sorry for taking so long to take a look at this. Can't what you're after be solved using the keypath API? Like this:

```swift
struct Person: Unboxable {
  let name: String
  let city: String
  let zip: String
  let state: String
  let street: String

  init(unboxer: Unboxer) {
    name = unboxer.unbox("name")
    city = address.unbox("address.city", isKeyPath: true)
    zip = address.unbox("address.zip", isKeyPath: true)
    state = address.unbox("address.state", isKeyPath: true)
    street = address.unbox("address.street", isKeyPath: true)
  }
}
```

**Comment by nubbel** [comment]
@JohnSundell Of course it can be solved using key paths. That's actually what I've said:
> Note: This can also be done with key paths, but requires the structure to be traversed multiple times in the unboxing process.

But isn't this whole library about convenience and safety? Can't JSON decoding be solved using dictionary subscription only, e.g. `city = dict["address"]?["city"] as? String`? 🙃
Of course it can, but it's neither convenient nor super safe.

Let me highlight the benefits of the proposed change:
* Convenience: It's much more convenient to have an `Unboxer` for a sub-structure than having to repeat the key path over and over again.
* Safety: A sub-unboxer allows me to express the constraint: "'address' might be missing, but if it's present it must have the fields 'city', 'zip', and 'street'".
* Performance: The sub-structure must only be traversed once instead of for each field in the sub-structure. It probably won't make much of a difference, though.
* Elegance: I especially like this solution, because it doesn't introduce any new concepts or new parameters to existing functions that make things more complicated. People already know what an `Unboxer` is and how to use it.

**Comment by nubbel** [comment]
> @clayellis: We aren't trying to solve the same problem. Mine is unsolved and yours has already been solved by the author.

Counter question: Couldn't your problem be solved using key paths, too? 😜

### Example (adapted from #73)

Usage:
```swift
let json = // Some UnboxableDictionary
let bar: Bar = try Unbox(json)
```

`Bar`:
```swift
struct Bar: Unboxable {
    let bar: Int
    init(unboxer: Unboxer) {
        bar = unboxed.unbox("foo.bar")
    }
}
```

With JSON:
```json
{
  "foo": 
  {
    "bar": 1
  }
}
```
It's just a matter of taste where you want to traverse into the substructure. Sometimes it's more useful at the call to `Unbox` (as in your case), but sometimes (as in my case) right in the `init`.

Anyway, I'm glad your PR has been merged. It's a useful addition to the library. 🎉

Still, I think this PR is useful just as well for the reasons mentioned above.

**Comment by JohnSundell** [comment]
@nubbel Sorry for not noticing your comment about key paths :/ You're of course right in that the goal of Unbox is to provide an easy - yet type safe and predictable - way to decode JSON, and we should always be making improvements towards that goal.

While I don't see key paths as "unsafe", you definitely have a point in terms of performance.

What I usually do to solve this exact problem is to use a nested structure, like this:

```swift
struct Person: Unboxable {
  let name: String
  let address: Adress

  init(unboxer: Unboxer) {
    name = unboxer.unbox("name")
    address = unboxer.unbox("address")
  }
}

struct Address: Unboxable {
  let city: String
  let zip: String
  let state: String
  let street: String

   init(unboxer: Unboxer) {
     city = address.unbox("city")
     zip = address.unbox("zip")
     state = address.unbox("state")
     street = address.unbox("street")
  }
}
```

This (IMO) strikes the balance between elegance, safety and performance. It's very similar to your proposed change (since the `Address` structure can be created inline in `Person.init` and be kept private), and already exists in Unbox. What do you think about this solution?

**Comment by nubbel** [comment]
@JohnSundell Yes, this is a perfect solution for this use case.

My concrete use case is the following. I receive data from a web service that looks like that:

```swift
let dictionary: UnboxableDictionary = [
	"info": [
		"name" : "nubbel",
		"email" : "nubbel@example.com"
	]
	// more data …
]
```

I want that data to be parsed into the `Person` struct:
```swift
struct Person {
	let name: String
	let email: String
}
```

The relevant part from the `WebService` class looks something like this:
```swift
final class WebService {
		func load<T: Unboxable, R: Resource where R.Model == T>(resource: R, completion: Result<T, WebServiceError> -> Void) {
		request(resource.url) { result in
			// closure used to simplify early returns
			completion({
				switch result {
				case .Success(let data):
					do {
						return .Success(try Unbox(data))
					}
					catch let error {
						return .Failure(.JSON(error))
					}
				case .Failure(let error):
					return .Failure(.InvalidResponse(error))
				}
			}())
		}
	}
}
```

These are all perfectly valid solutions *without modifications to `WebService`*:

1) Using key paths:
```swift
extension Person: Unboxable {
	init(unboxer: Unboxer) {
		name = unboxer.unbox("info.name")
		email = unboxer.unbox("info.email")
	}
}
```

2) Using inline struct:
```swift
extension Person: Unboxable {
	init(unboxer: Unboxer) {
		struct Info: Unboxable {
			let name: String
			let email: String

			init(unboxer: Unboxer) {
				name = unboxer.unbox("name")
				email = unboxer.unbox("email")
			}
		}

		let info: Info = unboxer.unbox("info")
		name = info.name
		email = info.email
	}
}
```

3) This PR would allow the usage of a sub-unboxer for the "info" path:
```swift
extension Person: Unboxable {
	init(unboxer: Unboxer) {
		let infoUnboxer: Unboxer = unboxer.unbox("info")
		name = infoUnboxer.unbox("name")
		email = infoUnboxer.unbox("email")
	}
}
```

Note that real model has way more fields.
With the first solution, every additional field would require the "info" sub-structure to be parsed once again.
With the second solution, every additional field would require changes to two more source locations.
With the third solution, the "info" substructure is parsed only once and no changes (besides the obvious) for additional fields are required.

A solution based on `Unbox(:at:)` (introduced in #92) would require modifications to `WebService` which I don't really want to do, because all the other responses from the API are not nested.

I hope this makes my intentions clear.

**Comment by JohnSundell** [comment]
A version of this has now been implemented in master. Since Unboxer now doesn't hold any state, its initializer has been exposed as public, so that the API user is free to create them whenever required. Thanks @nubbel and @clayellis for your work on this! 👍

**Comment by nubbel** [comment]
Thanks @JohnSundell!

**Pull request closed without merging**
