### PR TITLE
Support custom unboxing through a closure-based API

### PR DESCRIPTION
**Pull request by JohnSundell**
When Unbox is used in conjunction with CoreData, or other data sources, more fine-grained control over the unboxing process is sometimes needed. This PR introduces a new static API on `Unboxer` that enables an API user to handle the unboxing processs themselves, using a closure.

Resolves https://github.com/JohnSundell/Unbox/issues/18

### CODE REVIEW

**Comment by JohnSundell** [comment]
@rcdilorenzo Would this API support your usecase? :)

**Comment by rcdilorenzo** [comment]
Perfect! This should do the trick. Thanks so much for your responsiveness.

**Comment by rcdilorenzo** [comment]
I'd be happy to add an example to the README given the proper repo permissions.

**Comment by JohnSundell** [comment]
@rcdilorenzo Awesome! Feel free to open a PR with the README example if you want, and I'll merge it in :)

**Comment by JohnSundell** [comment]
Added a README example: https://github.com/JohnSundell/Unbox/commit/17a3383f8ac3f42c299097fde47604967e1dde55

**Pull request merged**
